---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "cert-management.fullname" . }}
  labels:
    helm.sh/chart: {{ include "cert-management.chart" . }}
    app.kubernetes.io/name: {{ include "cert-management.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
rules:
- apiGroups:
  - ""
  - extensions
  resources:
  - services
  - ingresses
  verbs:
  - get
  - list
  - update
  - watch
- apiGroups:
    - ""
  resources:
    - secrets
  verbs:
    - get
    - list
    - update
    - watch
    - create
    - delete
- apiGroups:
  - cert.gardener.cloud
  resources:
  - issuers
  - issuers/status
  - certificates
  - certificates/status
  verbs:
  - get
  - list
  - update
  - watch
  - create
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - get
  - list
  - update
  - create
