# SPDX-FileCopyrightText: 2019 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

nameOverride: ""
fullnameOverride: cert-controller-manager

replicaCount: 1

image:
  repository: eu.gcr.io/gardener-project/cert-controller-manager
  tag: v0.5.1
  pullPolicy: IfNotPresent

resources:
  requests:
   cpu: 100m
   memory: 64Mi
  limits:
   cpu: 200m
   memory: 128Mi

nodeSelector: {}
tolerations: []
affinity: {}
# priorityClassName: ""

createCRDs:
  issuers: true
  certificates: true

configuration:
  # acceptedMaintainers:
  # bindAddressHttp:
  # cascadeDelete:
  # certClass:
  # certTargetClass:
  # config:
  # controllers:
  # cpuprofile:
  # defaultIssuer:
  # defaultIssuerDomainRanges:
  # defaultRequestsPerDayQuota:
  # defaultPoolResyncPeriod:
  # defaultPoolSize:
  # disableNamespaceRestriction:
  # dns:
  # dnsClass:
  # dnsNamespace:
  # dnsOwnerId:
  # dnsDisableDeployCrds:
  # dnsId:
  # dnsMigrationIds:
  # forceCrdUpdate:
  # gracePeriod:
  # ingressCertCertClass:
  # ingressCertCertTargetClass:
  # ingressCertDefaultPoolResyncPeriod:
  # ingressCertDefaultPoolSize:
  # ingressCertPoolResyncPeriod:
  # ingressCertPoolSize:
  # ingressCertTargetNamePrefix:
  # ingressCertTargetNamespace:
  # ingressCertTargetsPoolSize:
  # issuerNamespace:
  # issuerCascadeDelete:
  # issuerCertClass:
  # issuerDefaultIssuer:
  # issuerDefaultIssuerDomainRanges:
  # issuerDefaultRequestsPerDayQuota:
  # issuerDefaultPoolResyncPeriod:
  # issuerDefaultPoolSize:
  # issuerDnsClass:
  # issuerDnsNamespace:
  # issuerDnsOwnerId:
  # issuerIssuerNamespace:
  # issuerIssuersPoolSize:
  # issuerPoolResyncPeriod:
  # issuerPoolSize:
  # issuerPrecheckAdditionalWait:
  # issuerPrecheckNameservers:
  # issuerPropagationTimeout:
  # issuerRenewalOverdueWindow:
  # issuerRenewalWindow:
  # issuerSecretsPoolSize:
  # issuersPoolSize:
  # kubeconfig:
  # kubeconfigDisableDeployCrds:
  # kubeconfigId:
  # kubeconfigMigrationIds:
  # leaseDuration:
  # leaseName:
  # leaseRenewDeadline:
  # leaseRetryPeriod:
  # logLevel:
  # maintainer:
  # namespace:
  # namespaceLocalAccessOnly:
  # omitLease:
  # pluginFile:
  # poolResyncPeriod:
  # poolSize:
  # precheckAdditionalWait:
  # precheckNameservers:
  # propagationTimeout:
  # renewalOverdueWindow:
  # renewalWindow:
  # secretsPoolSize:
  serverPortHttp: 8080
  # serviceCertCertClass:
  # serviceCertCertTargetClass:
  # serviceCertDefaultPoolResyncPeriod:
  # serviceCertDefaultPoolSize:
  # serviceCertPoolResyncPeriod:
  # serviceCertPoolSize:
  # serviceCertTargetNamePrefix:
  # serviceCertTargetNamespace:
  # serviceCertTargetsPoolSize:
  # source:
  # sourceDisableDeployCrds:
  # sourceId:
  # sourceMigrationIds:
  # target:
  # targetNamePrefix:
  # targetNamespace:
  # targetDisableDeployCrds:
  # targetId:
  # targetMigrationIds:
  # targetsPoolSize:
  # version:

additionalConfiguration: []
