# SPDX-FileCopyrightText: 2019 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: cert.gardener.cloud/v1alpha1
kind: Certificate
metadata:
  name: cert-wildcard
  namespace: default
spec:
  commonName: "*.cert2.martin.mydomain.com"
  issuerRef:
    name: issuer-staging
  # optionally specify secret to store certificate
  secretRef:
    name: cert-wildcard-secret
    namespace: default
  # optionally set labels for the secret
  #secretLabels:
  #  key1: value1
  #  key2: value2