# SPDX-FileCopyrightText: 2019 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: cert.gardener.cloud/v1alpha1
kind: Certificate
metadata:
  annotations:
    # class annotation only needed if cert-controller-manager is started with --cert-class=myclass
    #cert.gardener.cloud/class: myclass
  name: cert-simple-with-keystores
  namespace: default
spec:
  commonName: cert1.mydomain.com
  dnsNames:
  - cert1.my-other-domain.com
  # optionally specify secret to store certificate
  secretRef:
    name: cert-simple-secret
    namespace: default

  # enable keystore creation for both JKS and PKCS#12
  # This will create additional data entries in the certificate secret named `keystore.jks`, `truststore.jks` for JKS
  # and `keystore.p12`, `truststore.p12` for PKCS#12
  keystores:
    jks:
      create: true
      passwordSecretRef:
        secretName: keystore-secret
        key: password
    pkcs12:
      create: true
      passwordSecretRef:
        secretName: keystore-secret
        key: password
---
apiVersion: v1
kind: Secret
metadata:
  name: keystore-secret
  namespace: default
data:
  password: cGFzcw== # example password is `pass`