# SPDX-FileCopyrightText: 2019 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: echoheaders
  namespace: default
  annotations:
    cert.gardener.cloud/purpose: managed
spec:
  tls:
    - hosts:
        - echoheaders.demo.mydomain.com
      secretName: cert-echoheaders
  rules:
    - host: echoheaders.demo.mydomain.com
      http:
        paths:
          - backend:
              serviceName: echoheaders
              servicePort: 80
            path: /
